In [1]:
# https://pytorch.org/tutorials/beginner/blitz/autograd_tutorial.html

import torch

In [2]:
# uninitialized matrix

print(torch.empty(2, 3))

tensor([[7.5205e+28, 7.6286e-19, 7.1758e+22],
        [1.4349e-19, 2.7530e+12, 7.5338e+28]])


In [3]:
# randomly initialized matrix

print(torch.rand(2, 3))

tensor([[0.4763, 0.5496, 0.0581],
        [0.1202, 0.1448, 0.2057]])


In [6]:
# matrix filled with zeros and of different types

print(torch.zeros(2, 3, dtype = torch.long))
print(torch.zeros(2, 3, dtype = torch.double))
print(torch.zeros(2, 3, dtype = torch.float))

tensor([[0, 0, 0],
        [0, 0, 0]])
tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [12]:
# construct a tensor from given data

x = torch.tensor([[5.5, 3], [3.1, 2.99]])
print(x)

# create a tensor based on an existing tensor
# filled with ones

print(x.new_ones(2, 2, dtype = torch.int))

# filled with random numbers

print(torch.randn_like(x, dtype = torch.float))

tensor([[5.5000, 3.0000],
        [3.1000, 2.9900]])
tensor([[1, 1],
        [1, 1]], dtype=torch.int32)
tensor([[-1.0813,  1.8306],
        [ 0.1754,  1.5431]])


In [13]:
# print the size of a tensor
# torch.Size is a tuple

print(x.size())

torch.Size([2, 2])


In [15]:
# add

y = torch.rand(2, 2)
print(x + y)
print(torch.add(x, y))

tensor([[5.5842, 3.9909],
        [4.0435, 3.0597]])
tensor([[5.5842, 3.9909],
        [4.0435, 3.0597]])


In [16]:
# provide an output tensor

result = torch.empty(2, 2)
torch.add(x, y, out = result)
print(result)

tensor([[5.5842, 3.9909],
        [4.0435, 3.0597]])


In [17]:
# inplace add

y.add_(x)
print(y)

tensor([[5.5842, 3.9909],
        [4.0435, 3.0597]])


In [19]:
# resize

x = torch.randn(2, 8)
y = x.view(16)
z = x.view(-1, 4)
print(x.size(), y.size(), z.size())

torch.Size([2, 8]) torch.Size([16]) torch.Size([4, 4])


In [20]:
# get value of one element tensor

x = torch.randn(1)
print(x)
print(x.item())

tensor([1.6072])
1.6072430610656738
