In [1]:
import torch

In [2]:
# uninitialized matrix

print(torch.empty(2, 3))

tensor([[7.5205e+28, 7.6286e-19, 7.1758e+22],
        [1.4349e-19, 2.7530e+12, 7.5338e+28]])


In [3]:
# randomly initialized matrix

print(torch.rand(2, 3))

tensor([[0.4763, 0.5496, 0.0581],
        [0.1202, 0.1448, 0.2057]])


In [6]:
# matrix filled with zeros and of different types

print(torch.zeros(2, 3, dtype = torch.long))
print(torch.zeros(2, 3, dtype = torch.double))
print(torch.zeros(2, 3, dtype = torch.float))

tensor([[0, 0, 0],
        [0, 0, 0]])
tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [12]:
# construct a tensor from given data

x = torch.tensor([[5.5, 3], [3.1, 2.99]])
print(x)

# create a tensor based on an existing tensor
# filled with ones

print(x.new_ones(2, 2, dtype = torch.int))

# filled with random numbers

print(torch.randn_like(x, dtype = torch.float))

tensor([[5.5000, 3.0000],
        [3.1000, 2.9900]])
tensor([[1, 1],
        [1, 1]], dtype=torch.int32)
tensor([[-1.0813,  1.8306],
        [ 0.1754,  1.5431]])


In [13]:
# print the size of a tensor
# torch.Size is a tuple

print(x.size())

torch.Size([2, 2])
